FROM mcr.microsoft.com/devcontainers/python:1-3.10-bullseye

#ADD https://raw.githubusercontent.com/cboettig/rl-minicourse/main/requirements.txt /tmp/requirements.txt
#RUN chmod a+rw /tmp/requirements.txt
#USER vscode
#RUN pip3 install --user -r /tmp/requirements.txt
#USER root

